name: Bundle Audit Checks
on: [push, workflow_dispatch]

jobs:
  build:
    name: Bundle Audit Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose run --rm app ruby test/hello_test.rb
